# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
dist:
  - bionic
julia:
  - 1.0
  - 1.3
  - nightly
addons:
  apt:
    update: true
    packages:
    - libqhull-r7
    - libqhull-dev
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

