# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
dist:
  - bionic
julia:
  - 1.0
  - nightly
addons:
  apt:
    update: true
    packages:
    - libqhull-r7
    - libqhull-dev
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  include:
    - stage: Documentation
      julia: 1.0
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          Pkg.build();
          include("docs/make.jl");'
      after_success: skip
