name = "MiniQhull"
uuid = "978d7f02-9e05-4691-894f-ae31a51d76ca"
authors = ["Francesc Verdugo <fverdugo@cimne.upc.edu>", "Victor Sande <vsande@cimne.upc.edu>"]
version = "0.4.0"

[deps]
Qhull_jll = "784f63db-0788-585a-bace-daefebcd302b"

[compat]
Qhull_jll = "v2019.1.0, v2020.2.0"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[targets]
test = ["Test", "StaticArrays"]
